version: '3.9'
services:
  app:
    platform: linux/amd64
    build:
      context: .
      target: dev
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - ./public:/app/public
    command: npm run dev
